# Generated by Django 4.2 on 2023-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='product name')),
                ('price', models.PositiveIntegerField(verbose_name='product price')),
                ('img', models.ImageField(upload_to='media', verbose_name='product img')),
            ],
        ),
    ]
